name: Ruff Linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
      - run: ruff check --output-format=github .
      - run: ruff format --check
